# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineOne', models.CharField(max_length=50)),
                ('LineTwo', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('endDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=14)),
                ('Email', models.EmailField(max_length=254)),
                ('addressLineOne', models.CharField(max_length=50)),
                ('addressLineTwo', models.CharField(max_length=50)),
                ('addressCity', models.CharField(max_length=50)),
                ('addressCountry', models.CharField(max_length=50)),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Booking')),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='user',
            new_name='userID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='property',
            name='assignedName',
            field=models.CharField(default='UNDEFINED', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='UNDEFINED', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.URLField(max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='propertyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Property'),
        ),
        migrations.AddField(
            model_name='address',
            name='propertyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Property'),
        ),
    ]
